version: "3.8"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.8
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - prometheus-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

networks:
  prometheus-network:
