# my global config
global:
  scrape_interval: 5s
  evaluation_interval: 10s

rule_files:
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'ordem-servico-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['0.0.0.0:8081'] #Funcionou apenas pegando o IP do computador, digita: hostname -I

#localhost docker.internal.host